Init authentication
mszymczak710/WellVibeWeb pull request #1
Opened 2023-10-16 18:46 UTC by mszymczak710

2023-10-17 05:51 UTC, Dulniko requested changes

2023-10-17 05:51 UTC, Dulniko commented on WellVibeWebAPI/accounts/mixins.py
> +class PasswordResetMixin:
po co mixin, będzie to gdzieś indziej używane?

2023-10-17 05:51 UTC, Dulniko commented on WellVibeWebAPI/accounts/admin.py
> +admin.site.register(User, UserAdminConfig)
możesz użyć dekoratora dla admina

2023-10-17 05:51 UTC, Dulniko commented on WellVibeWebAPI/accounts/serializers.py
> +        fields = ["email", "role", "first_name", "last_name"]
czemu lista?

2023-10-17 05:51 UTC, Dulniko commented on WellVibeWebAPI/core/settings.py
> +EMAIL_USE_TLS = bool(os.environ.get('EMAIL_USE_TLS', 'True'))
po co to rzutujesz?

2023-10-17 07:25 UTC, Dulniko requested changes

2023-10-17 07:25 UTC, Dulniko commented on WellVibeWebAPI/accounts/signals.py
> +    if created and instance.role == "PATIENT":
Mozesz używać stałą zamiast stringa

2023-10-18 07:11 UTC, icorvus commented on WellVibeWebAPI/accounts/views.py
> +                )
brakuje tłumaczenie błędów za pomocą gettext

2023-10-18 07:12 UTC, icorvus commented on WellVibeWebAPI/accounts/views.py
> +            return Response({"detail": str(e)}, status=status.HTTP_400_BAD_REQUEST)
nie wydaje mi się, że przekazywanie użytkownikowi pythonowych błędów to dobry pomysł

2023-10-18 17:08 UTC, mszymczak710 commented on .gitignore
> +WellVibeWebAPI/logs
Poprawione.

2023-10-18 17:08 UTC, mszymczak710 commented on WellVibeWebAPI/accounts/views.py
> +                )
Poprawione.

2023-10-18 17:08 UTC, mszymczak710 commented on WellVibeWebAPI/accounts/signals.py
> +    if created and instance.role == "PATIENT":
Poprawione.

2023-10-18 17:08 UTC, mszymczak710 commented on WellVibeWebAPI/core/settings.py
> +EMAIL_USE_TLS = bool(os.environ.get('EMAIL_USE_TLS', 'True'))
Nie wiem, przypadkowo, poprawiłem to już

2023-10-18 17:09 UTC, mszymczak710 commented on WellVibeWebAPI/accounts/mixins.py
> +class PasswordResetMixin:
W sumie nie, usunąłem.

2023-10-18 17:10 UTC, mszymczak710 commented on WellVibeWebAPI/accounts/admin.py
> +admin.site.register(User, UserAdminConfig)
Poprawiłem.

2023-10-20 20:55 UTC, closed without merging